### PR TITLE
Bug 2032924: PVs are not being cleaned up after PVC deletion

### PR DESCRIPTION
**Pull request by dobsonj**
This PR:
1) Rebases the openshift fork on [the commit](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/commit/c96e27d784e290b048976ef3053eb90cb77d00f7) being [used by LSO](https://github.com/openshift/local-storage-operator/blob/843d3cadfcae3f68ef267387a2deffbc57a217b3/go.mod#L34) today.
2) Adds a carry patch with a fix for https://bugzilla.redhat.com/show_bug.cgi?id=2032924 on top of the rebase

Comparison to upstream:
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/compare/master...dobsonj:rebase-master-20210414
/cc @gnufied @jsafrane

### CODE REVIEW

**Comment by gnufied** [comment]
Can we also test with this version vendored and see if we can reproduce the bug?

**Comment by dobsonj** [comment]
> Can we also test with this version vendored and see if we can reproduce the bug?

Yeah, working on it
/hold

**Comment by dobsonj** [comment]
To test this fix, I added this line to go.mod in local-storage-operator:
```
replace sigs.k8s.io/sig-storage-local-static-provisioner => github.com/dobsonj/sig-storage-local-static-provisioner v0.0.0-20220208192914-b5e1aa52a4e3
```
Then ran `go mod vendor`. The only changes under vendor were the expected changes from the carry patch:
```
        modified:   vendor/modules.txt
        modified:   vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.
go
        modified:   vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/dele
ter.go
```
Then used `./hack/sync_bundle` to build `quay.io/jdobson/index:bug2032924`.
And followed the steps in the bug to attempt to reproduce it.
In the diskmaker logs, I see the cache entry gets marked as clean:
```
I0208 20:23:56.038173  948792 reconcile.go:101] Deleting PVs through sig storage deleter
I0208 20:23:56.048731  948792 cache.go:100] Marked pv "local-pv-e739fe1b" as cleaned in the cache
I0208 20:23:56.048768  948792 deleter.go:169] Deleting pv local-pv-e739fe1b after successful cleanup
```
There are a couple of calls to DeletePVs() after that, but they do not start a second cleanup job while the cache entry still exists:
```
I0208 20:23:56.058225  948792 reconcile.go:46] "Looking for released PVs to cleanup" namespace="openshift-local-storage" name="local-provisioner"
I0208 20:23:56.058942  948792 common.go:345] StorageClass "lv-loop0" configured with MountDir "/mnt/local-storage/lv-loop0", HostDir "/mnt/local-storage/lv-loop0", VolumeMode "Filesystem", FsType "xfs", BlockCleanerCommand ["/scripts/quick_reset.sh"], NamePattern "*"
I0208 20:23:56.059005  948792 reconcile.go:101] Deleting PVs through sig storage deleter
I0208 20:23:56.059095  948792 cache.go:69] Updated pv "local-pv-e739fe1b" to cache
I0208 20:23:56.059127  948792 reconcile.go:207] "found PV with state released" pvName="local-pv-e739fe1b"
I0208 20:23:56.059448  948792 reconcile.go:46] "Looking for released PVs to cleanup" namespace="openshift-local-storage" name=""
I0208 20:23:56.059610  948792 common.go:345] StorageClass "lv-loop0" configured with MountDir "/mnt/local-storage/lv-loop0", HostDir "/mnt/local-storage/lv-loop0", VolumeMode "Filesystem", FsType "xfs", BlockCleanerCommand ["/scripts/quick_reset.sh"], NamePattern "*"
I0208 20:23:56.059693  948792 reconcile.go:101] Deleting PVs through sig storage deleter
I0208 20:23:56.059771  948792 cache.go:69] Updated pv "local-pv-e739fe1b" to cache
I0208 20:23:56.059841  948792 reconcile.go:256] "Reconciling LocalVolume" namespace="openshift-local-storage" name="lv-loop0"
I0208 20:23:56.060042  948792 common.go:345] StorageClass "lv-loop0" configured with MountDir "/mnt/local-storage/lv-loop0", HostDir "/mnt/local-storage/lv-loop0", VolumeMode "Filesystem", FsType "xfs", BlockCleanerCommand ["/scripts/quick_reset.sh"], NamePattern "*"
I0208 20:23:56.067385  948792 cache.go:79] Deleted pv "local-pv-e739fe1b" from cache
I0208 20:23:56.067284  948792 cache.go:79] Deleted pv "local-pv-e739fe1b" from cache
```
Since there is no duplicate cleanup job created, there is no leftover successful job status to find on the next attempt. I see only 1 file each time the PVC/Pod is created using this PV (i.e. no leftover files from previous pods).
/unhold

**Comment by gnufied** [comment]
The diff seems sensible.

/lgtm

**Pull request merged**
